project       = "test-mala-calc"
appname       = "calc"
location      = ["HA", "LV"]
image         = "gcr.io/test-mala-calc/calc-image:latest"
port          = 80
max_instances = 5
min_instances = 1
revision      = true
environment = "dev"